'use client';

import { useState } from 'react';
import { useCart } from '@/context/CartContext';

type Design = { id: string; title: string; occasion: string | null; fabric: string | null; estimatedPrice: number; generatedImageUrl: string | null; mainColor: string; dressType: string; sleeveStyle: string | null; neckStyle: string | null; length: string | null; embroidery: string | null };
export default function SavedDesignsClient({ initialDesigns }: { initialDesigns: Design[] }) {
  const { addItem } = useCart(); const [designs, setDesigns] = useState(initialDesigns); const [message, setMessage] = useState('');
  const rename = async (design: Design) => { const title = window.prompt('Rename this design', design.title); if (!title || title === design.title) return; const response = await fetch(`/api/ai/designs/${design.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title }) }); if (response.ok) setDesigns((items) => items.map((item) => item.id === design.id ? { ...item, title } : item)); };
  const remove = async (id: string) => { if (!window.confirm('Delete this saved design?')) return; const response = await fetch(`/api/ai/designs/${id}`, { method: 'DELETE' }); if (response.ok) setDesigns((items) => items.filter((item) => item.id !== id)); };
  const reuse = (design: Design) => { addItem({ productId: 'custom-design-request', name: `Customization request — ${design.title}`, slug: 'custom-frock-request', price: design.estimatedPrice, image: design.generatedImageUrl || '', size: '4Y', quantity: 1, customization: { color: design.mainColor, fabric: design.fabric || undefined, sleeve: design.sleeveStyle || undefined, neck: design.neckStyle || undefined, length: design.length || undefined, embroidery: design.embroidery || undefined } }); setMessage('Customization request added to your bag.'); };
  return <>{message && <p className="text-muted text-sm mb-4">{message}</p>}<div className="product-grid">{designs.map((design) => <article key={design.id} className="product-card"><div className="product-card-image">{design.generatedImageUrl ? <img src={design.generatedImageUrl} alt={design.title} /> : <div style={{ display: 'grid', placeItems: 'center', height: '100%', background: 'var(--cream-soft)' }}>Concept</div>}</div><div className="product-card-body"><p className="product-card-name">{design.title}</p><p style={{ fontSize: '12px', color: 'var(--earth-taupe)', marginTop: '4px' }}>{design.occasion || 'Custom'} • {design.fabric || 'Custom fabric'}</p><p className="product-card-price" style={{ marginTop: '8px' }}>PKR {design.estimatedPrice.toLocaleString()}</p><div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap', marginTop: '12px' }}><button className="btn btn-primary btn-sm" onClick={() => reuse(design)}>Request customization</button><button className="btn btn-ghost btn-sm" onClick={() => rename(design)}>Rename</button><button className="btn btn-ghost btn-sm" onClick={() => remove(design.id)}>Delete</button></div></div></article>)}</div></>;
}
