const outfits = [
  {
    name: 'Sage Botanica Lawn Set',
    slug: 'sage-botanica-lawn-set',
    categorySlug: 'everyday-frocks',
    price: 6490, discountPrice: 5790,
    fabric: 'Premium Printed Lawn',
    colors: 'Sage Green, Ivory, Soft Olive',
    occasion: 'Everyday, Brunch, Summer Dawat',
    style: 'Straight Shirt with Wide-Leg Culotte',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 18, sku: 'DHG-ADL-021',
    tags: 'sage, botanical, lawn, culotte, summer, printed, everyday, Pakistani',
    isFeatured: true, isNewArrival: true, isCustomizable: true,
    rating: 4.8, reviewCount: 18,
    shortDescription: 'A calm sage botanical print paired with a clean straight shirt and fluid culotte for effortless summer dressing.',
    description: 'Designed around a soft botanical print, this breathable lawn set balances relaxed tailoring with a polished Pakistani silhouette. The straight shirt has a neat neckline and the wide-leg culotte keeps the look easy for daytime wear.',
    images: ['/products/floral-bloom-lawn-frock.jpg'], imagePlaceholder: true
  },
  {
    name: 'Ivory Bloom Cotton Kurta',
    slug: 'ivory-bloom-cotton-kurta',
    categorySlug: 'everyday-frocks',
    price: 5990, discountPrice: 5290,
    fabric: 'Soft Cotton with Schiffli-Inspired Texture',
    colors: 'Ivory, Pearl White, Sage',
    occasion: 'Everyday, Office, Family Lunch',
    style: 'Straight Kurta with Tapered Pants',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 20, sku: 'DHG-ADL-022',
    tags: 'ivory, cotton, kurta, schiffli, minimal, white, everyday, pret',
    isFeatured: false, isNewArrival: true, isCustomizable: true,
    rating: 4.7, reviewCount: 12,
    shortDescription: 'An airy ivory kurta with delicate texture and tailored pants for a refined everyday wardrobe.',
    description: 'The soft ivory base keeps this look versatile while subtle textured detailing adds depth without becoming heavy. A straight kurta and tapered trouser create a clean silhouette suitable for workdays and casual gatherings.',
    images: ['/products/lavender-bloom-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Terracotta Block Garden Suit',
    slug: 'terracotta-block-garden-suit',
    categorySlug: 'everyday-frocks',
    price: 6790, discountPrice: 5990,
    fabric: 'Printed Cotton Lawn',
    colors: 'Terracotta, Sand, Olive',
    occasion: 'Daywear, Brunch, Summer Gatherings',
    style: 'Block-Print Shirt with Straight Trouser',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 16, sku: 'DHG-ADL-023',
    tags: 'terracotta, block print, lawn, cotton, trouser, summer, earthy, printed',
    isFeatured: false, isNewArrival: false, isCustomizable: false,
    rating: 4.8, reviewCount: 21,
    shortDescription: 'Earthy terracotta tones and artisan-inspired print work make this two-piece a warm everyday statement.',
    description: 'A warm terracotta palette gives the classic Pakistani lawn suit a contemporary feel. The printed shirt is paired with a straight trouser and restrained detailing for an outfit that feels expressive without being overly formal.',
    images: ['/products/rose-garden-tiered-frock.jpg'], imagePlaceholder: true
  },
  {
    name: 'Powder Blue Linework Co-ord',
    slug: 'powder-blue-linework-coord',
    categorySlug: 'everyday-frocks',
    price: 6290, discountPrice: 5490,
    fabric: 'Lightweight Printed Cambric',
    colors: 'Powder Blue, White, Mist Grey',
    occasion: 'Casual, Travel, Weekend',
    style: 'Longline Shirt with Wide-Leg Trouser',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 22, sku: 'DHG-ADL-024',
    tags: 'powder blue, co-ord, cambric, stripes, wide leg, casual, modern',
    isFeatured: false, isNewArrival: false, isCustomizable: true,
    rating: 4.6, reviewCount: 9,
    shortDescription: 'A fresh powder-blue linework print with a relaxed longline shirt and wide-leg trouser.',
    description: 'This modern co-ord uses clean linear patterning to create a crisp, elongated look. The lightweight cambric construction makes it practical for warm days while the wide-leg trouser adds a contemporary finish.',
    images: ['/products/teal-heritage-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Rose Quartz Embroidered Pret',
    slug: 'rose-quartz-embroidered-pret',
    categorySlug: 'party-wear',
    price: 8490, discountPrice: 7490,
    fabric: 'Embroidered Cambric',
    colors: 'Rose Quartz, Cream, Dusty Mauve',
    occasion: 'Dawat, Dinner, Semi-Formal',
    style: 'Embroidered Long Shirt with Straight Trouser',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 14, sku: 'DHG-PRT-025',
    tags: 'rose quartz, embroidered, cambric, pret, dinner, mauve, elegant',
    isFeatured: true, isNewArrival: true, isCustomizable: true,
    rating: 4.9, reviewCount: 26,
    shortDescription: 'Soft rose tones meet tonal embroidery in an elegant pret look made for intimate occasions.',
    description: 'The rose-quartz base is enriched with fine tonal embroidery around the neckline and hem. A long shirt and straight trouser keep the silhouette sophisticated while maintaining the ease of ready-to-wear dressing.',
    images: ['/products/lavender-bloom-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Plum Threadwork Two-Piece',
    slug: 'plum-threadwork-two-piece',
    categorySlug: 'party-wear',
    price: 8790, discountPrice: 7790,
    fabric: 'Premium Cotton Cambric with Thread Embroidery',
    colors: 'Deep Plum, Blush, Antique Beige',
    occasion: 'Dinner, Evening Dawat, Festive Casual',
    style: 'Long A-Line Shirt with Cigarette Trouser',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 12, sku: 'DHG-PRT-026',
    tags: 'plum, threadwork, embroidered, two piece, cambric, evening, pret',
    isFeatured: false, isNewArrival: true, isCustomizable: true,
    rating: 4.8, reviewCount: 17,
    shortDescription: 'Deep plum cotton cambric with fine threadwork creates a rich yet wearable evening silhouette.',
    description: 'A saturated plum ground gives this two-piece a confident evening character. Delicate thread embroidery follows the neckline and hem while the A-line shirt falls over a streamlined cigarette trouser.',
    images: ['/products/teal-heritage-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Mustard Heritage Kurta Set',
    slug: 'mustard-heritage-kurta-set',
    categorySlug: 'party-wear',
    price: 8190, discountPrice: 7190,
    fabric: 'Textured Cotton with Embroidered Details',
    colors: 'Mustard, Ivory, Olive',
    occasion: 'Dawat, Festive Lunch, Family Events',
    style: 'Embroidered Kurta with Straight Pants',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 15, sku: 'DHG-PRT-027',
    tags: 'mustard, heritage, kurta, embroidered, cotton, olive, festive',
    isFeatured: false, isNewArrival: false, isCustomizable: true,
    rating: 4.7, reviewCount: 13,
    shortDescription: 'A warm mustard kurta with heritage-inspired embroidery and an understated straight trouser.',
    description: 'Mustard brings energy to this structured cotton set, while restrained embroidery gives the kurta a traditional touch. The straight pants balance the silhouette and make the outfit easy to style with flats or embroidered khussas.',
    images: ['/products/floral-bloom-lawn-frock.jpg'], imagePlaceholder: true
  },
  {
    name: 'Seafoam Print & Culotte Set',
    slug: 'seafoam-print-culotte-set',
    categorySlug: 'party-wear',
    price: 7590, discountPrice: 6690,
    fabric: 'Printed Premium Lawn',
    colors: 'Seafoam, White, Pale Peach',
    occasion: 'Brunch, Eid Day, Summer Party',
    style: 'Printed Shirt with Pleated Culotte',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 19, sku: 'DHG-PRT-028',
    tags: 'seafoam, lawn, culotte, printed, pastel, summer, brunch, eid',
    isFeatured: false, isNewArrival: true, isCustomizable: false,
    rating: 4.8, reviewCount: 15,
    shortDescription: 'A breezy seafoam print paired with a fluid pleated culotte for fresh festive-day styling.',
    description: 'Soft seafoam and pale peach create a light, celebratory palette. The printed shirt is cut with a clean neckline and paired with a pleated culotte that gives the two-piece movement and a contemporary finish.',
    images: ['/products/rose-garden-tiered-frock.jpg'], imagePlaceholder: true
  },
  {
    name: 'Emerald Noor Festive Set',
    slug: 'emerald-noor-festive-set',
    categorySlug: 'eid-collection',
    price: 10990, discountPrice: 9490,
    fabric: 'Silk-Blend with Embroidered Organza',
    colors: 'Emerald, Antique Gold, Ivory',
    occasion: 'Eid, Chand Raat, Festive Dinner',
    style: 'Embroidered 3-Piece Kurta, Trouser and Dupatta',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 11, sku: 'DHG-EID-029',
    tags: 'emerald, eid, festive, embroidered, organza, gold, three piece, silk',
    isFeatured: true, isNewArrival: true, isCustomizable: true,
    rating: 5.0, reviewCount: 31,
    shortDescription: 'Jewel-toned emerald, antique-gold detailing and an airy dupatta create a polished Eid ensemble.',
    description: 'This festive three-piece set pairs a rich emerald kurta with refined antique-gold embroidery. The matching trouser keeps the base elegant while the lightweight organza dupatta adds a graceful final layer for Eid gatherings.',
    images: ['/products/teal-heritage-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Coral Jacquard Eid Kurta',
    slug: 'coral-jacquard-eid-kurta',
    categorySlug: 'eid-collection',
    price: 9990, discountPrice: 8690,
    fabric: 'Textured Jacquard with Chiffon Dupatta',
    colors: 'Coral, Champagne, Warm Ivory',
    occasion: 'Eid, Milad, Festive Brunch',
    style: 'Long Jacquard Kurta with Straight Trouser',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 13, sku: 'DHG-EID-030',
    tags: 'coral, jacquard, eid, chiffon, festive, champagne, kurta, formal',
    isFeatured: false, isNewArrival: true, isCustomizable: true,
    rating: 4.9, reviewCount: 23,
    shortDescription: 'A luminous coral jacquard kurta finished with champagne accents for an elegant Eid look.',
    description: 'The textured jacquard surface gives the coral kurta subtle dimension without relying on heavy embellishment. Champagne detailing and a soft chiffon dupatta complete the look with a refined festive mood.',
    images: ['/products/lavender-bloom-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Midnight Luxe Winter Suit',
    slug: 'midnight-luxe-winter-suit',
    categorySlug: 'eid-collection',
    price: 11490, discountPrice: 9990,
    fabric: 'Velvet-Touch Textured Fabric',
    colors: 'Midnight Navy, Silver, Deep Teal',
    occasion: 'Winter Festive, Dinner, Formal Eid',
    style: 'Long Straight Kurta with Embellished Neckline',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 9, sku: 'DHG-EID-031',
    tags: 'midnight, navy, winter, velvet, festive, silver, formal, eid',
    isFeatured: true, isNewArrival: false, isCustomizable: true,
    rating: 4.8, reviewCount: 19,
    shortDescription: 'A deep midnight winter ensemble with subtle silver accents for sophisticated evening occasions.',
    description: 'The dark navy base gives this winter suit a luxurious depth, while restrained silver detailing defines the neckline and cuffs. Its long straight silhouette is designed to feel formal without becoming cumbersome.',
    images: ['/products/teal-heritage-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Champagne Organza Formal Set',
    slug: 'champagne-organza-formal-set',
    categorySlug: 'wedding-collection',
    price: 12990, discountPrice: 11490,
    fabric: 'Raw Silk with Organza Panels',
    colors: 'Champagne, Sand, Antique Gold',
    occasion: 'Walima, Engagement, Formal Dinner',
    style: 'Structured Long Shirt with Wide Trouser and Organza Dupatta',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 8, sku: 'DHG-WED-032',
    tags: 'champagne, organza, raw silk, walima, formal, gold, wedding',
    isFeatured: true, isNewArrival: true, isCustomizable: true,
    rating: 4.9, reviewCount: 27,
    shortDescription: 'Champagne raw silk and sheer organza details create an understated formal wedding look.',
    description: 'A warm champagne palette gives this formal set a refined glow. Structured raw silk is softened with sheer organza panels and a matching dupatta, creating a balanced silhouette for engagements and evening receptions.',
    images: ['/products/lavender-bloom-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Ruby Zari Wedding Ensemble',
    slug: 'ruby-zari-wedding-ensemble',
    categorySlug: 'wedding-collection',
    price: 15990, discountPrice: 13990,
    fabric: 'Premium Raw Silk with Zari-Inspired Embroidery',
    colors: 'Ruby Red, Antique Gold, Maroon',
    occasion: 'Wedding, Barat, Mehndi Evening',
    style: 'Embroidered Long Shirt with Gharara and Dupatta',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 8, sku: 'DHG-WED-033',
    tags: 'ruby, wedding, zari, gharara, raw silk, gold, barat, formal',
    isFeatured: true, isNewArrival: true, isCustomizable: true,
    rating: 5.0, reviewCount: 34,
    shortDescription: 'Ruby raw silk with antique-gold inspired embroidery creates a dramatic wedding-ready ensemble.',
    description: 'The ruby base provides a rich canvas for fine gold-inspired embroidery concentrated around the shirt and borders. A flowing gharara and coordinated dupatta complete the traditional occasion silhouette with a polished modern cut.',
    images: ['/products/rose-garden-tiered-frock.jpg'], imagePlaceholder: true
  },
  {
    name: 'Lilac Sharara Wedding Edit',
    slug: 'lilac-sharara-wedding-edit',
    categorySlug: 'wedding-collection',
    price: 14990, discountPrice: 12990,
    fabric: 'Embroidered Chiffon and Silk-Blend',
    colors: 'Dusty Lilac, Pearl, Soft Silver',
    occasion: 'Walima, Baraat, Engagement',
    style: 'Short Kurti with Flared Sharara and Dupatta',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 10, sku: 'DHG-WED-034',
    tags: 'lilac, sharara, walima, chiffon, silver, wedding, pastel',
    isFeatured: false, isNewArrival: true, isCustomizable: true,
    rating: 4.9, reviewCount: 22,
    shortDescription: 'Dusty lilac, pearl detailing and a fluid sharara create a soft contemporary wedding edit.',
    description: 'A muted lilac palette keeps the formal look romantic and modern. The short kurti carries delicate surface work while the flared sharara creates movement beneath a lightweight dupatta for wedding celebrations.',
    images: ['/products/lavender-bloom-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Teal Antique-Gold Anarkali',
    slug: 'teal-antique-gold-anarkali',
    categorySlug: 'wedding-collection',
    price: 15490, discountPrice: 13490,
    fabric: 'Silk-Blend with Organza and Embroidery',
    colors: 'Deep Teal, Antique Gold, Cream',
    occasion: 'Mehndi, Wedding Dinner, Festive Formal',
    style: 'Flared Anarkali with Straight Trouser and Dupatta',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 9, sku: 'DHG-WED-035',
    tags: 'teal, anarkali, antique gold, wedding, mehndi, silk, formal',
    isFeatured: true, isNewArrival: false, isCustomizable: true,
    rating: 4.8, reviewCount: 29,
    shortDescription: 'Deep teal and antique-gold accents frame a graceful flared Anarkali silhouette.',
    description: 'This formal Anarkali combines a saturated teal base with antique-gold inspired embroidery along the bodice and flare. A clean trouser and sheer dupatta keep the overall look balanced and elegant.',
    images: ['/products/teal-heritage-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Blush Rose Gharara Set',
    slug: 'blush-rose-gharara-set',
    categorySlug: 'wedding-collection',
    price: 13990, discountPrice: 11990,
    fabric: 'Soft Silk with Embroidered Net Dupatta',
    colors: 'Blush Rose, Nude, Champagne',
    occasion: 'Engagement, Nikkah, Bridal Shower',
    style: 'Peplum Kurti with Gharara and Net Dupatta',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 12, sku: 'DHG-WED-036',
    tags: 'blush, rose, gharara, nikkah, peplum, silk, champagne, wedding',
    isFeatured: false, isNewArrival: false, isCustomizable: true,
    rating: 4.7, reviewCount: 16,
    shortDescription: 'A blush rose peplum and fluid gharara form a soft occasion look with feminine movement.',
    description: 'The blush base is complemented by champagne detailing and a lightweight embroidered net dupatta. A fitted peplum balances the volume of the gharara, making the outfit suitable for intimate wedding functions.',
    images: ['/products/rose-garden-tiered-frock.jpg'], imagePlaceholder: true
  },
  {
    name: 'Noir Ivory Minimal Co-ord',
    slug: 'noir-ivory-minimal-coord',
    categorySlug: 'new-arrivals',
    price: 7390, discountPrice: 6490,
    fabric: 'Premium Cotton Blend',
    colors: 'Black, Ivory, Soft Taupe',
    occasion: 'Dinner, City Wear, Contemporary Events',
    style: 'Minimal Long Shirt with Relaxed Wide-Leg Trouser',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 20, sku: 'DHG-CNT-037',
    tags: 'black, ivory, co-ord, minimal, wide leg, contemporary, cotton',
    isFeatured: false, isNewArrival: true, isCustomizable: false,
    rating: 4.8, reviewCount: 11,
    shortDescription: 'A black-and-ivory palette gives this relaxed Pakistani co-ord a sharp contemporary identity.',
    description: 'Clean contrast does the work in this minimal set, pairing an elongated ivory shirt with a black relaxed trouser. Small construction details keep the outfit polished while leaving room for statement accessories.',
    images: ['/products/vintage-polka-dot-frock.jpg'], imagePlaceholder: true
  },
  {
    name: 'Olive Utility Kurta Co-ord',
    slug: 'olive-utility-kurta-coord',
    categorySlug: 'new-arrivals',
    price: 7690, discountPrice: 6690,
    fabric: 'Textured Cotton Twill',
    colors: 'Olive, Cream, Sand',
    occasion: 'Weekend, Travel, Casual Lunch',
    style: 'Utility-Inspired Kurta Shirt with Straight Trouser',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 17, sku: 'DHG-CNT-038',
    tags: 'olive, utility, co-ord, cotton, casual, modern, travel, sand',
    isFeatured: false, isNewArrival: true, isCustomizable: true,
    rating: 4.6, reviewCount: 8,
    shortDescription: 'Utility-inspired details reinterpret the Pakistani kurta in a relaxed olive co-ord.',
    description: 'The olive cotton twill gives this contemporary set a structured but comfortable feel. Utility-style pockets and clean topstitching add character while the straight trouser keeps the silhouette wearable.',
    images: ['/products/floral-bloom-lawn-frock.jpg'], imagePlaceholder: true
  },
  {
    name: 'Cobalt Azure Wide-Leg Set',
    slug: 'cobalt-azure-wide-leg-set',
    categorySlug: 'new-arrivals',
    price: 7290, discountPrice: 6390,
    fabric: 'Printed Lawn with Soft Cotton Trouser',
    colors: 'Cobalt Blue, White, Azure',
    occasion: 'Brunch, Summer Events, Casual Festive',
    style: 'Printed Long Shirt with Wide-Leg Trouser',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 21, sku: 'DHG-CNT-039',
    tags: 'cobalt, blue, printed lawn, wide leg, summer, co-ord, Pakistani',
    isFeatured: false, isNewArrival: false, isCustomizable: false,
    rating: 4.7, reviewCount: 14,
    shortDescription: 'Bold cobalt print and a wide-leg trouser give this lightweight set a confident summer finish.',
    description: 'Cobalt and azure tones create a graphic but wearable printed shirt. The wide-leg trouser echoes the relaxed proportions and keeps the look modern for daytime events and summer gatherings.',
    images: ['/products/teal-heritage-kurta-set.jpg'], imagePlaceholder: true
  },
  {
    name: 'Peach Petal Statement Kurta',
    slug: 'peach-petal-statement-kurta',
    categorySlug: 'new-arrivals',
    price: 7990, discountPrice: 6990,
    fabric: 'Premium Lawn with Embroidered Neckline',
    colors: 'Soft Peach, Cream, Coral',
    occasion: 'Dawat, Eid Day, Brunch',
    style: 'Statement Straight Kurta with Pleated Culotte',
    availableSizes: 'XS, S, M, L, XL', ageRange: 'Adult',
    stockQuantity: 18, sku: 'DHG-CNT-040',
    tags: 'peach, kurta, culotte, lawn, embroidered, eid, pastel, statement',
    isFeatured: false, isNewArrival: true, isCustomizable: true,
    rating: 4.9, reviewCount: 20,
    shortDescription: 'A soft peach statement kurta with fine neckline embroidery and a flowing pleated culotte.',
    description: 'Soft peach creates a fresh base for the fine embroidered neckline and cuffs. The pleated culotte adds movement and modern volume, making the outfit easy to dress up with traditional jewellery or keep understated.',
    images: ['/products/rose-garden-tiered-frock.jpg'], imagePlaceholder: true
  }
];

module.exports = outfits;
